KEYWORDS: dict[str, list[str]] = {
    # one-way-channels
    "website": [
        "website",
        "web site",
        "homepage",
        "home page",
        "project website",
        "official website",
        "project page",
        "project homepage",
    ],
    "blog": [
        "blog",
    ],
    "rss_feed": [
        "rss",
        "rss feed",
        "atom",
        "atom feed",
        "feed",
        "subscribe via rss",
        "subscribe to rss",
        "subscribe to the feed",
    ],
    "medium": [
        "medium",
        "medium com",
        "on medium",
        "medium blog",
        "medium publication",
    ],

    # chat
    "gitter": [
        "gitter",
        "gitter im",
        "gitter chat",
        "gitter room",
        "join gitter",
    ],
    "discord": [
        "discord",
        "discord server",
        "discord channel",
        "join discord",
        "join our discord",
        "discord invite",
        "invite to discord",
    ],
    "slack": [
        "slack",
        "slack workspace",
        "slack channel",
        "join slack",
        "request an invite to slack",
        "slack invite",
        "invite to slack",
    ],
    "patreon": [
        "patreon",
        "support us on patreon",
        "become a patron",
        "patron",
    ],
    "zulip": [
        "zulip",
        "zulip chat",
        "zulip stream",
        "join zulip",
    ],
    "icq": [
        "icq",
    ],
    "telegram": [
        "telegram",
        "telegram group",
        "telegram channel",
        "join telegram",
        "t me",
    ],
    "irc": [
        "irc",
        "internet relay chat",
        "irc channel",
        "join irc",
        "freenode",
        "libera chat",
        "liberachat",
        "oftc",
        "quakenet",
    ],

    # forum
    "forum": [
        "forum",
        "community forum",
        "support forum",
        "discussion forum",
        "message board",
        "bulletin board",
        "discourse",
        "discourse forum",
        "community.discourse",
    ],
    "stack_overflow": [
        "stack overflow",
        "stackoverflow",
    ],
    "reddit": [
        "reddit",
        "subreddit",
        "r ",
        "ask on reddit",
        "post on reddit",
    ],

    # personal
    "meetup": [
        "meetup",
        "meetup com",
        "meetup group",
        "meetup event",
        "join a meetup",
    ],
    "skype": [
        "skype",
        "skype chat",
        "skype group",
        "call us on skype",
    ],

    # mail-related
    "newsletter": [
        "newsletter",
        "subscribe to our newsletter",
        "subscribe to the newsletter",
        "mailing newsletter",
        "email newsletter",
        "news letter",
    ],
    "mailing_list": [
        "mailing list",
        "mailing-list",
        "mail list",
        "mailman",
        "listserv",
        "join the mailing list",
        "subscribe to the mailing list",
        "unsubscribe",
        "announce list",
        "announce mailing list",
        "users mailing list",
        "dev mailing list",
        "developers mailing list",
        "user list",
        "dev list",
    ],
    "mail": [
        "email",
        "e mail",
        "mail",
        "contact us",
        "contact the team",
        "reach out",
        "write to us",
        "send an email",
        "send us an email",
        "email us",
        "mail us",
    ],
    "form": [
        "contact form",
        "feedback form",
        "request form",
        "support form",
        "submit the form",
        "fill out the form",
        "google form",
        "google forms",
        "typeform",
        "form",
    ],
    "google_group": [
        "google group",
        "google groups",
        "googlegroups",
        "google mailing list",
        "groups google com",
    ],

    # social media
    "youtube": [
        "youtube",
        "you tube",
        "youtube channel",
        "subscribe on youtube",
        "watch on youtube",
    ],
    "facebook": [
        "facebook",
        "fb",
        "facebook page",
        "facebook group",
        "follow on facebook",
    ],
    "twitter": [
        "twitter",
        "x com",
    ],
    "linkedin": [
        "linkedin",
        "linked in",
        "linkedin page",
        "linkedin group",
        "follow on linkedin",
    ],

    # ticket system
    "jira": [
        "jira",
        "atlassian jira",
        "jira project",
        "jira board",
        "open a jira ticket",
        "file a jira ticket",
    ],
    "issues": [
        "issue",
        "issues",
        "bug",
        "bugs",
        "bug report",
        "bug reports",
        "feature request",
        "feature requests",
        "open an issue",
        "file an issue",
        "create an issue",
        "report an issue",
        "report a bug",
        "submit an issue",
        "issue tracker",
        "bug tracker",
        "ticket",
        "tickets",
        "open a ticket",
        "file a ticket",
        "submit a ticket",
        "tracker",
    ],

    # GitHub channels
    "github_issues": [
        "github issues",
        "github issue",
        "github issue tracker",
        "open a github issue",
        "file a github issue",
        "create a github issue",
        "report on github",
        "issue on github",
        "issues on github",
    ],
    "pull_request": [
        "github pull request",
        "pull request",
        "pull-request",
        "pr",
        "submit a pr",
        "open a pr",
        "submit a pull request",
        "open a pull request",
        "create a pull request",
        "send a pull request",
        "make a pull request",
    ],
    "fork": [
        "fork",
        "forks",
        "fork the repo",
        "fork this repo",
        "fork this repository",
        "fork on github",
        "create a fork",
    ],
    "ping_on_github": [
        "ping on github",
        "ping us on github",
        "mention on github",
        "mention us on github",
        "tag on github",
        "tag us on github",
        "cc on github",
        "cc us on github",
        "github mention",
        "github ping",
    ],
    "github_wiki": [
        "github wiki",
        "wiki",
        "project wiki",
        "repository wiki",
        "the wiki",
        "update the wiki",
        "check the wiki",
    ],
    "github_discussions": [
        "github discussions",
        "discussion",
        "discussions",
        "start a discussion",
        "open a discussion",
        "create a discussion",
        "ask in discussions",
        "github discussion",
    ],
}