from datetime import datetime

__all__ = [
    "DO_NOT_CLASSIFY_AT_ALL",
    "DO_NOT_EXPORT_CHANGES",
    "ONLY_CLASSIFY_THIS_MANY_COMMITS_PER_REPO",
    "RANDOM_STATE",
    "RANDOM_STATE_FOR_DRAWING_EVENTS",
    "EVENTS_SAMPLE_SIZE",
    "DELETE_GIT_DIR_IMMEDIATELY",
    "SAMPLE_SIZE",
    "SINCE",
    "UNTIL",
    "PATHS_TO_CONSIDER",
    "PARTS_OF_BASE_OUTPUT_DIR",
    "NAME_OF_SAMPLES_DIR",
    "NAME_OF_COMMITS_DIR",
    "NAME_OF_FRAMES_DIR",
    "NAME_OF_CHANGES_DIR",
    "NAME_OF_RESULTS_DIR",
    "NAME_OF_TEST_RESULTS_DIR",
    "ASSUME_MAXIMUM_OF_ONE_DELTA_PER_FILE",
    "CONTEXT_LINES",
]

# development
DO_NOT_CLASSIFY_AT_ALL = False
DO_NOT_EXPORT_CHANGES = True
ONLY_CLASSIFY_THIS_MANY_COMMITS_PER_REPO = 10 # ignored if not > 0

# reproducibility
RANDOM_STATE = 44
RANDOM_STATE_FOR_DRAWING_EVENTS = 42

# manual labeling
EVENTS_SAMPLE_SIZE = 100

DELETE_GIT_DIR_IMMEDIATELY = False
SAMPLE_SIZE = 10
SINCE = datetime(2023, 1, 1)
UNTIL = datetime(2025, 11, 30, 23, 59, 59)

_README = "README"
_CONTRIBUTING = "CONTRIBUTING"
PATHS_TO_CONSIDER = [
    _README + ".md",
    _README.lower() + ".md",
    _README + ".txt",
    _README.lower() + ".txt",
    _CONTRIBUTING + ".md",
    _CONTRIBUTING.lower() + ".md",
    _CONTRIBUTING + ".txt",
    _CONTRIBUTING.lower() + ".txt",
]

PARTS_OF_BASE_OUTPUT_DIR = [
    "data",
    "output"
]
NAME_OF_SAMPLES_DIR = "samples"
NAME_OF_COMMITS_DIR = "commits"
NAME_OF_FRAMES_DIR = "frames"
NAME_OF_CHANGES_DIR = "changes"
NAME_OF_RESULTS_DIR = "results"
NAME_OF_TEST_RESULTS_DIR = "test results"

# diffing options:
ASSUME_MAXIMUM_OF_ONE_DELTA_PER_FILE = True
CONTEXT_LINES = 0